### ISSUE TITLE
Project documentation issue

### ISSUE THREAD

**Issue by Sahil-Mukund-Jadhav** [kunaltyagi9/Electricity-Billing-System#3]
The diagrams which you have uploaded in your documents are not in the proper format, it is not visible clearly so please if possible send me the diagrams related to this project in a pdf format or word file.

**Comment by kunaltyagi9** [comment]
I have not prepared any documentation of any of my project, All are contributed by viewers. Will advice you to prepare the document yourself with the help of what I have attached in the description of the video.

If possible, please share your documentation so that others can be benefited too. 
I think I have answered your query. So, closing this issue

**Comment by Sahil-Mukund-Jadhav** [comment]
yes sure
